name: 'Artifact Upload Job'

on:
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

jobs:
  run-python:
    name: Run python
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      # Install bdip wheel
      - name: Install wheel
        run: pip install wheel
        
      # Build wheel file
      - name: Build wheel
        run: python setup.py bdist_wheel
        
       # Install your twine here
      - name: Install twine
        run: pip install twine
        
       # Google Authetication
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
          service_account: 'artifact-test@sat-app-dev.iam.gserviceaccount.com'

        
      # Upload artifact to Artifact Registry
      - name: Upload to Artifact Registry
        run: python3 -m twine upload --repository-url https://us-east4-python.pkg.dev/sat-app-dev/test/ dist/*
